### ISSUE TITLE
k8:// line gives invalid path error

### ISSUE THREAD

**Issue by Vaishali2896** [buger/goreplay#1080]
I am trying to create a daemon set, I have a service deployed already in namespace: cms-test.
My file looks like
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goreplay-daemon
spec:
  template:
    spec:
      hostNetwork: true
      serviceAccountName: goreplay
      containers:
      - name: goreplay
        image: buger/goreplay:latest
        command:
          - "--input-raw k8s://default/pod/nginx-deployment-6588ff5bdd-4cc7c"
          - "--output-file requests.log"
But I am getting this error whenever I try to run it
stat --input-raw    k8s://cms-test/pod/cms-api-67f778dc5b-5wk2g: no such file or directory: unknown

**Comment by yqbjtu** [comment]
where to get the buger/goreplay:2.0.0-rc2 image?  do you build it by yourself?

**Comment by monrax** [comment]
The `command` option doesn't work with the `"./gor"` entrypoint. Use `args` instead:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goreplay-daemon
spec:
  selector:
    matchLabels:
      app: goreplay
  template:
    metadata:
      labels:
        app: goreplay
    spec:
      hostNetwork: true
      serviceAccountName: goreplay
      containers:
        - name: goreplay
      image: buger/goreplay:latest
      args:
        - "--input-raw"
        - "k8s://default/pod/nginx-deployment-6588ff5bdd-4cc7c"
        - "--output-file requests.log"
```
