### ISSUE TITLE
How to use goreplay in kubernetes

### ISSUE THREAD

**Issue by Jsen1234** [buger/goreplay#766]
I am wondering how can I use goreplay in Kubernetes. Is there any way to start goreplay within the pods? Or I need to install it in the node where Nginx-ingress is installed? Basically I am just checking if someone already integrated goreplay in Kubernetes.

**Comment by slimus** [comment]
@Jsen1234 HI! Can you please add a little bit more information about your task. Do you want to capture all Kubernetes traffic or only from your pod?

**Comment by MonojitBanerjee** [comment]
Hey slimus Thanks for checking. I just want to replay traffic from my pods. Let's say I have a production service with 4 pods and I have test instance. I want these 4 pods to replay traffic to this test instance. Is that possible using goreplay at all? Also, FYI I am using nginx ingress to route the traffic from load balancer to the service(and to the pods).

**Comment by Jsen1234** [comment]
Hey @slimus Thanks for checking. I just want to replay traffic from my pods. Let's say I have a production service with 4 pods and I have test instance. I want these 4 pods to replay traffic to this test instance. Is that possible using goreplay at all? Also, FYI I am using nginx ingress to route the traffic from load balancer to the service(and to the pods).

**Comment by Jsen1234** [comment]
Hey @slimus Just checking if you have any suggestions on this.

**Comment by slimus** [comment]
Hi @Jsen1234 ! We discussed your issue with team. I want to try create example and write config a little bit later

**Comment by nimiew** [comment]
I need this too.

**Comment by cameronbraid** [comment]
Just build a container using the Dockerfile in git, add it as a container to your pod and it works

I have two containers in a pod one is a http server (plaintext) on 8080 and another as below is gor

```
        - image: drivenow~goreplay
          name: goreplay
          command:
            - /gor
            
            - --input-raw
            - :8080
            
            - --output-kafka-host
            - kafka-kafka-bootstrap:9092
            
            - --output-kafka-topic
            - goreplay

            - --output-kafka-json-format
```
